### ISSUE TITLE
Remove -m flag requirement when -e is flagged

### ISSUE THREAD

**Issue by nolanbconaway** [AusterweilLab/jarjar#4]
`jarjar -e "Hello"` should work like `jarjar -e -m "Hello"`. Who's with me?

**Comment by jeffzemla** [comment]
Sounds good. Or maybe just jarjar -m "Hello" ?

**Comment by nolanbconaway** [comment]
![](https://media.tenor.com/images/5938bc7536735b184c639395d4c1d465/tenor.gif)

**Comment by nolanbconaway** [comment]
covered in jarjar 3 by #10
